<?php


/**
 * Skeleton subclass for representing a row from the 'hl_jugadores' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov 20 21:36:25 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class HlJugadores extends BaseHlJugadores {

	/**
	 * Initializes internal state of HlJugadores object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
  
  public function __toString()
  {
    return $this->getNombre()." (".$this->getHlDepartamentos()->getDepartamento().")";
  }
  
  public function esHombrelobo()
  {
    return $this->getHombrelobo() > 0;
  }
  
  public function esAlcalde()
  {
    return $this->getAlcalde() > 0;
  }
  
  public function esVidente()
  {
    return $this->getVidente() > 0;
  }
  
  public function estaEnamorado()
  {
    return $this->getEnamorado() > 0;
  }
  
  public function getAmante()
  {
    if($this->getEnamorado() > 0)
    {
      $c = new Criteria();
      $c->add(HlJugadoresPeer::ENAMORADO,$this->getEnamorado());
      $c->add(HlJugadoresPeer::ID,$this->getId(),CRITERIA::NOT_EQUAL);
      $pareja = HlJugadoresPeer::doSelectOne($c);
      if($pareja instanceof HlJugadores) 
        return $pareja;
    }
    
    return $this; //Nunca debería llegar aquí
  }
  
  public function esCazador()
  {
    return $this->getCazador() > 0;
  }
  
  public function esBruja()
  {
    return $this->getBruja() > 0;
  }
  
  public function esPuta()
  {
    return $this->getPuta() > 0;
  }
  
  public function estaEnfermo()
  {
    return $this->getEnfermo() > 0;
  }
  
  
 
        

} // HlJugadores
