<?php


/**
 * Skeleton subclass for performing query and update operations on the 'hl_votos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov 20 22:52:30 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class HlVotosPeer extends BaseHlVotosPeer {

} // HlVotosPeer
