propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  hl_comentarios:
    _attributes: { phpName: HlComentarios }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    id_jugador: { phpName: IdJugador, type: INTEGER, size: '11', required: false, foreignTable: hl_jugadores, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    id_noticia: { phpName: IdNoticia, type: INTEGER, size: '11', required: true, foreignTable: hl_noticias, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    texto: { phpName: Texto, type: CLOB, required: true }
    fecha: { phpName: Fecha, type: TIMESTAMP, required: true }
    _indexes: { id_noticia: [id_noticia], id_jugador: [id_jugador] }
  hl_departamentos:
    _attributes: { phpName: HlDepartamentos }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    departamento: { phpName: Departamento, type: VARCHAR, size: '255', required: true }
  hl_estado:
    _attributes: { phpName: HlEstado }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    ronda: { phpName: Ronda, type: INTEGER, size: '2', required: true }
    fase: { phpName: Fase, type: VARCHAR, size: '10', required: true }
    vidente: { phpName: Vidente, type: TINYINT, size: '1', required: true }
    pocion_vida: { phpName: PocionVida, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    pocion_muerte: { phpName: PocionMuerte, type: TINYINT, size: '1', required: true, defaultValue: '0' }
  hl_jugadores:
    _attributes: { phpName: HlJugadores }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '40', required: true }
    id_departamento: { phpName: IdDepartamento, type: INTEGER, size: '11', required: true, foreignTable: hl_departamentos, foreignReference: id, onDelete: RESTRICT, onUpdate: CASCADE }
    alias: { phpName: Alias, type: VARCHAR, size: '40', required: true }
    foto: { phpName: Foto, type: VARCHAR, size: '255', required: true }
    usuario: { phpName: Usuario, type: VARCHAR, size: '128', required: true }
    contrasena: { phpName: Contrasena, type: VARCHAR, size: '128', required: true }
    email: { phpName: Email, type: VARCHAR, size: '40', required: true }
    descripcion: { phpName: Descripcion, type: CLOB, required: true }
    activo: { phpName: Activo, type: TINYINT, size: '1', required: true, defaultValue: '1' }
    hombrelobo: { phpName: Hombrelobo, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    alcalde: { phpName: Alcalde, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    vidente: { phpName: Vidente, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    enamorado: { phpName: Enamorado, type: INTEGER, size: '1', required: true, defaultValue: '0' }
    bruja: { phpName: Bruja, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    cazador: { phpName: Cazador, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    enfermo: { phpName: Enfermo, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    puta: { phpName: Puta, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    accion: { phpName: Accion, type: TINYINT, size: '1', required: true, defaultValue: '0' }
    _indexes: { id_departamento: [id_departamento], hombrelobo: [hombrelobo, alcalde, vidente, enamorado, bruja, cazador, enfermo, puta] }
  hl_noticias:
    _attributes: { phpName: HlNoticias }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    id_jugador: { phpName: IdJugador, type: INTEGER, size: '11', required: false, foreignTable: hl_jugadores, foreignReference: id, onDelete: RESTRICT, onUpdate: CASCADE }
    fecha: { phpName: Fecha, type: TIMESTAMP, required: true }
    titulo: { phpName: Titulo, type: VARCHAR, size: '255', required: true }
    noticia: { phpName: Noticia, type: CLOB, required: true }
    foto_noticia: { phpName: FotoNoticia, type: VARCHAR, size: '255', required: true }
    _indexes: { id_jugador: [id_jugador] }
  hl_votos:
    _attributes: { phpName: HlVotos }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    id_ronda: { phpName: IdRonda, type: INTEGER, size: '2', required: true, index: 'true' }
    id_jugador: { phpName: IdJugador, type: INTEGER, size: '11', required: true, foreignTable: hl_jugadores, foreignReference: id, onDelete: RESTRICT, onUpdate: CASCADE }
    id_victima: { phpName: IdVictima, type: INTEGER, size: '11', required: true, foreignTable: hl_jugadores, foreignReference: id, onDelete: RESTRICT, onUpdate: CASCADE }
    _indexes: { id_jugador: [id_jugador], id_victima: [id_victima] }
